services:
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  mongodb: 
    image: mongodb:v1
    container_name: mongodb


networks:
  default: 
    driver: bridge
    name: robo-dock
    external: false




